### ISSUE TITLE
Get voucher list directly by using Shopify API

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#13]

**Comment by dwdowns** [comment]
This is low priority for now thanks

**Comment by dwdowns** [comment]
Hi - are we able to re-open this and see if we can do something quickly? We are having an issue where people are buying vouchers and turning up to the stores immediately so the venue doesn't know about them. I wonder if we can implement a data pull from shopify directly to the portal page.
I'm in work meets for a few hours but can describe it better later what I am thinking

**Comment by johndowns** [comment]
Ok. Can you tell me what the data type in Shopify is - is it called a
voucher or is it an order or something else?

**Comment by dwdowns** [comment]
An order
https://shopify.dev/docs/admin-api/rest/reference/orders/order


David Downs
david@downsy.co.nz<mailto:david@downsy.co.nz>
021758967

**Comment by johndowns** [comment]
Can you let me know when you are free to talk

**Comment by dwdowns** [comment]
> > I'm in work meets for a few hours

Free at 12.30

David Downs
david@downsy.co.nz<mailto:david@downsy.co.nz>
021758967

**Comment by johndowns** [comment]
OK, I will try for a call then but will see how I go.

One of the things I need from you in order to progress this is exactly what
steps you go through today to pull down the voucher data and prepare it for
upload. Can you write this up in as much excruciating detail as possible?
For example:

   - Where do you go to get the export today
   - Do you put any filters when you export the data
   - Once it's downloaded, what format is it in
   - What do you do to manipulate the data to prepare it for upload to the
   portal, e.g.
      - Do you hide/remove any columns
      - Do you rename any columns
      - Do you manipulate any rows
      - Do you change formats of any columns

**Comment by dwdowns** [comment]
Lets talk at 11 if you are free?

David Downs
david@downsy.co.nz<mailto:david@downsy.co.nz>
021758967

**Comment by johndowns** [comment]
Yes 11 should be good

**Comment by johndowns** [comment]
As per this evening's investigation, here is how we would calculate each of the fields we currently store using the Shopify API's `Order` model:

| Portal Entity  | Source |
| - | - |
| `CustomerAcceptsMarketing` | `buyer_accepts_marketing` |
| `CustomerEmailAddress` | `customer.email` |
| `CustomerName` | `customer.first_name + ' ' + customer.last_name` |
| `CustomerRegion` | `customer.default_address.city` |
| `IsRefunded` | *See below* |
| `LineItemId`  | `line_items.id`  |
| `OrderDate` | `created_at` |
| `OrderId` | `id` |
| `OrderRef` | `name` |
| `VendorId` | `line_items.product_id` |
| `VoucherDescription` | `line_items.variant_title` |
| `VoucherFees` | *See below* |
| `VoucherGross` | `line_items.price * line_items.quantity` |
| `VoucherId` | `line_items.properties['name eq "Voucher id"'].value` |
| `VoucherIsDonation` | *Will be removed in favour of `VoucherType`* |
| `VoucherNet` | *See below* |
| `VoucherQuantity`  | `line_items.quantity`  |
| `VoucherType` | `line_items.properties['name eq "Type"'].value` |

## Refunds

* Consider a line item to be refunded if its `line_item_id` appears as the `line_item_id` within the `refunds.refund_line_items` collection.

## Calculating fees

Calculate these parameters:
* `numberLineItemsInOrder` = `order.line_items.count()`
* `paymentGatewayName` = `order.gateway`
* `voucherGross` = `line_items.price * line_items.quantity`

```csharp
private decimal CalculateFees(int numberLineItemsInOrder, string paymentGatewayName, decimal voucherGross)
{
    decimal percentageFees;
    switch (paymentGatewayName)
    {
        case "shopify_payments":
            percentageFees = voucherGross * 0.035;
            break;
        case "poli_internet_banking":
            percentageFees = voucherGross * 0.01;
            break;
        default:
            percentageFees = voucherGross * 0.04;
            break;
    }

    decimal fixedFees;
    switch (paymentGatewayName)
    {
        case "shopify_payments":
            fixedFees = (0.3 / numberLineItemsInOrder);
            break;
        case "poli_internet_banking":
            fixedFees = 0;
            break;
        default:
            fixedFees = (0.45 / numberLineItemsInOrder);
            break;
    }

    return (percentageFees.Round(2) + fixedFees.Round(2)).Round(2);
}
```

**Comment by johndowns** [comment]
@dwdowns let me know if any of the above looks incorrect

**Comment by dwdowns** [comment]
Cool – for now I think this looks great; hopefully we can do a side by side comparison of data to test

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz/>
Check out my TEDx talk<https://www.ted.com/talks/david_downs_don_t_humour_the_tumour_beating_cancer_with_science_and_optimism>.

**Comment by johndowns** [comment]
Yes, I’m planning on storing the Shopify-obtained vouchers in a separate table. We can keep using the old table while the new data comes in, and do comparisons and spot checks as needed.

**Comment by dwdowns** [comment]
Cool – the other thing to keep in mind then is we may need to track the redemption in a separate table too, which can then link by the lineitem ID to either of the two tables.

David Downs
david@downsy.co.nz<mailto:david@downsy.co.nz>
021758967

**Comment by johndowns** [comment]
We already do that :)
