### ISSUE TITLE
Allow some way business can track which vouchers have been redeemed

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#26]
A button or box on the voucher screen? (Must be resilient for if we upload new data sets though so needs to be in a different table)

**Comment by johndowns** [comment]
@JackDownsNZ Here’s a proposal - let me know if this is workable from your side.

On the GET /vendors/{vendorId}/vouchers response there will be a new property on each voucher - dateRedeemed (a datetime - null if not redeemed).

On the UI there will be some way of showing that a voucher has been redeemed (I.e. that dateRedeemed is not null). David suggested a button on the non-redeemed vouchers that triggers them to be redeemed.

To redeem a voucher, you’ll do a PATCH on /vendors/{vendorId}/vouchers/{voucherId) and set the dateRedeemed to the time the user clicked the button.

Sound ok?

**Comment by JackDownsNZ** [comment]
@johndowns Yea that sounds fine from my side!

**Comment by johndowns** [comment]
@dwdowns Do you think we will need to account for vouchers being 'unredeemed' - e.g. accidental redemptions?

**Comment by JackDownsNZ** [comment]
What if someone accidentally click Redeem on a voucher that they didn't mean to? Maybe we need a two step process on the front end?

Ha! Same thought!

**Comment by JackDownsNZ** [comment]
Also... is it possible to partially redeem a voucher? e.g. $10 from a $50 voucher...

**Comment by dwdowns** [comment]
Yes but for the purposes of what you are doing we aren’t going to track that. The POS can track that

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by dwdowns** [comment]
Yes – this isn’t meant to be perfect, just a way for the vendor to mark them off. If they do that by mistake we should allow them to unclick it too

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by JackDownsNZ** [comment]
Cool - you have all the right answers! Thanks!

John - does the fact that they are able to untick them too make a difference to you here? Or do we just reset the value to null if they do untick?

**Comment by johndowns** [comment]
Yeah just set to null please. I will look at this tomorrow

**Comment by JackDownsNZ** [comment]
Working Branch: `voucher-redeem`

**Comment by JackDownsNZ** [comment]
@johndowns I've got the front end side pretty much ready. Let me know once the backend is ready and Ill test it out.

**Comment by JackDownsNZ** [comment]
@johndowns front end is now ready. Just need backend to pass the dateRedeemed object so I can test.

**Comment by johndowns** [comment]
@JackDownsNZ I have just merged my branch into yours, so the `voucher-redeem` branch has all of these changes on it. I also merged master onto that branch. Can you please check the merge didn't screw anything up, since it was a large merge.

I am still working on the back-end for this but hoping it will be done soon.

**Comment by johndowns** [comment]
Also just to be clear @JackDownsNZ - to update a voucher's redemption status you need to use the `PATCH` API, with the URL `/vendors/{vendorId}/vouchers/{voucherId}` - and note that `{voucherId}` in that URL is the voucher's `lineItemId`, NOT the `voucherId` (confusing, I know... sorry)

**Comment by johndowns** [comment]
@JackDownsNZ I've committed the core changes, but haven't fully tested them yet. Hopefully can do a bit of testing this evening.

**Comment by JackDownsNZ** [comment]
@johndowns cool have updated the frontend to reflect that (PATCH & lineItemId) - have tested but coming back with 404. Will look into my side as its most likely front end issue.

**Comment by johndowns** [comment]
No it's becaue that branch isn't deployed. I am sorting out another branch
first and will let you know when ready.

**Comment by johndowns** [comment]
Also the front-end build is failing @JackDownsNZ - I can't deploy the API changes to the test environment until it's fixed.

https://github.com/johndowns/soscafe/pull/90/checks?check_run_id=619365074

**Comment by JackDownsNZ** [comment]
Looks like dateRedeemed doesn't exist (at least on the business I'm using to test - 4349964779576)

```
customerAcceptsMarketing: false
customerEmailAddress: "erinahern.nz@gmail.com"
customerName: "Erin Ahern"
customerRegion: "New Plymouth"
lineItemId: "4338186879032"
orderDate: "2020-04-11T20:05:00Z"
orderId: "1926090227768"
orderRef: "8764"
voucherDescription: "$25"
voucherFees: 0.65
voucherGross: 25
voucherId: "09D2-EC5C-EED5-7D17-FEF2"
voucherIsDonation: false
voucherNet: 24.35
voucherQuantity: 1
__proto__: Object
```

**Comment by johndowns** [comment]
Yes as per my above comment, the branch with the API changes isn't deployed and I can't deploy until the front-end build works

**Comment by JackDownsNZ** [comment]
Ah ok sorry just saw that now - have pushed my frontend changes.
