### ISSUE TITLE
Change voucher data model - donation is now a string

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#31]
Due to a change in the way we track vouchers, would it be possible to change a field on the Voucher import? Currently there is a field called ‘isDonation’ which is with blank or TRUE.

Would like to change it to ‘VoucherType’ which will be a string (currently values are ‘Voucher’ and ‘Donation’)

**Comment by johndowns** [comment]
@dwdowns are you ready for me to make this change now? Do we need to synchronise it with changes to your CSV files?

**Comment by dwdowns** [comment]
Cool – No I think you can just change. I will update the file once you’re done

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
Covered by changes we are making to import vouchers from Shopify
