### ISSUE TITLE
Add administrative interface

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#35]
Feature set:
* Search for vendor by company name, vendor ID, email address, tag
* Read-only view of what the vendor sees - details, payments, vouchers
* Update a single string 'tag' field, which the vendor can't see
* Export vendor list (implemented already, but would need to be moved)

This could work using a custom attribute to act as a role claim. The front-end would then need to have a hidden route that shows the above features. The APIs would only work for users with that role claim; ideally the front-end would inspect that claim and not even try to talk to the API - ideally it would redirect the user back to the homepage if they don't have the right claim.

@JackDownsNZ do you think the above is feasible in the front-end app?

**Comment by JackDownsNZ** [comment]
@johndowns im getting a 404 when trying to download vendor list via `GET /internal/vendors/csv`

**Comment by JackDownsNZ** [comment]
also getting a 404 when searching for vendor using `GET /internal/vendors?vendorId=xxx&name=yyy&emailAddress=zzz&tag=xxx`

Have made sure that the vendor im searching for does exist. Been searching by Name, Email and ID

**Comment by johndowns** [comment]
Yeah that's because the latest PRs have overwritten that branch's deployment. Give me a few mins and I'll re-deploy that branch

**Comment by JackDownsNZ** [comment]
Ah darn thanks!

**Comment by johndowns** [comment]
Yeah we only have one test environment, so the last PR to deploy to it will overwrite anything else.

The PR is updated and the test API shuold be updated in the next few mins (https://github.com/johndowns/soscafe/pull/42/checks?check_run_id=598766134)

**Comment by JackDownsNZ** [comment]
Hm still no luck - might be my end, but im trying to process this below and its coming up with 404

https://soscafevendor-test.azurewebsites.net//internal/vendors?vendorId=${searchTerm}&name=${searchTerm}&emailAddress=${searchTerm}&tag=${searchTerm}

where searchTerm = 4351379800086 (vendor ID for Admin Test Business - owned by john+admintest user)

It should work but still getting 404.

**Comment by JackDownsNZ** [comment]
Scratch the above - got it working

**Comment by JackDownsNZ** [comment]
@johndowns are we adding the view for Payments & Vouchers for each business under Admin view? Noticed it wasn't in your above API details. Ive added the functionality anyway.
