### ISSUE TITLE
Integrate 'click and collect' opt-in integrated with MailChimp

### ISSUE THREAD

**Issue by joyceqnz** [johndowns/soscafe#53]
Can we connect mailchimp or sendgrid with the vendor portal, so that when vendors opt in to C&C, they get an automated email with information. Similar to the vendor sign up flow, but for a Click & Collect email instead. This is so that we don't have to manually pull a list everyday, vlookup who we contacted the day before and then manually reach out to them with the same messaging.

**Comment by johndowns** [comment]
@dwdowns thoughts on this?

**Comment by dwdowns** [comment]
Not sure this is required any more... I think its been superceded

**Comment by johndowns** [comment]
@dwdowns can you confirm if this is still required and if not can you close the issue please?

**Comment by dwdowns** [comment]
It was joyce who asked for it...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dwdowns** [comment]
But I will Check and let you know

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johndowns** [comment]
@joyceqnz Hey Joyce, is this still something you'd like?
