### ISSUE TITLE
Pick Up/Delivery checkboxes in Vendor Portal

### ISSUE THREAD

**Issue by joyceqnz** [johndowns/soscafe#56]
Vendors are able to check "I can do Pick Ups" and/or "I can do Delivery" in the Vendor portal which then passes through to Shopify and tags products "Pick" and/or "Delivery". We have created a new section on the site so customers can filter by vendors in their area who offer Pick Up and Delivery as a directory in Level 3.

**Comment by JackDownsNZ** [comment]
Working Branch: `pickup-delivery`

**Comment by JackDownsNZ** [comment]
@joyceqnz is pickup the same as click & collect?

**Comment by johndowns** [comment]
@joyceqnz once you answer Jack's question I can sort out the back-end implementation and we should be able to get this done pretty quickly.

**Comment by JackDownsNZ** [comment]
@johndowns just talked to joyce - not the same, you all good to setup those options? Front end is pretty much ready

**Comment by johndowns** [comment]
OK so just to be clear, there will be three separate checkboxes:
* Enabled for click and collect
* Enabled for pickup
* Enabled for delivery

Correct?

**Comment by JackDownsNZ** [comment]
yep!

i have them named as:

isClickAndCollect
isPickup
isDelivery

**Comment by JackDownsNZ** [comment]
@johndowns FYI - this change isn't to be launched just yet, as there needs to be some work done on the Shopify end. Joyce will email us in advance letting us know when to push live. Most likely this weekend.

**Comment by johndowns** [comment]
OK. I will probably do the API side sooner though, and then you can
make/merge the front-end part whenever. Sound ok?

**Comment by johndowns** [comment]
API changes have been made, and a draft PR has been created to test this out on the test environment. Are you ok to give it a go?

**Comment by johndowns** [comment]
This has been replaced by #73
