### ISSUE TITLE
Change services tag to service upon business creation

### ISSUE THREAD

**Issue by JackDownsNZ** [johndowns/soscafe#59]
Correction for vendor-new form. Shopify must receive the tag _service_ not _services_.

**Comment by JackDownsNZ** [comment]
Working Branch: `service-fix`

**Comment by JackDownsNZ** [comment]
@johndowns are there any changes in the backend that need to be done as well for this?

**Comment by johndowns** [comment]
@JackDownsNZ backend is done and on same branch. Can you open a PR when ready
