### ISSUE TITLE
add a field for the click and collect to the vendor upload

### ISSUE THREAD

**Issue by dwdowns** [johndowns/soscafe#63]
We are nearly finished with the vendor upload, but I realised when I uploaded a set last night it removed the C&C field that people had filled in. is it easy to add this field to the upload so I can re-instate the setting? Saves about an hour of manual updates so if it will take longer than that then don;t worry

**Comment by johndowns** [comment]
You should be able to do this right now - the field name is `Click and Collect`

(If you do a vendor export, the CSV format that that emits is exactly what you can import.)

**Comment by dwdowns** [comment]
Ah cool! thanks

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
Is this existing functionality OK @dwdowns? Can we close this issue?

**Comment by dwdowns** [comment]
Yes it works fine now thanks

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.
