### ISSUE TITLE
Add a field or something to hide the vendor

### ISSUE THREAD

**Issue by dwdowns** [johndowns/soscafe#70]
We have a number of duplicate records - mostly because people set themselves up twice. We catch these in shopify and don't show duplicates but we'd like a way to not display duplicates on the portal.
EG search for 'Laundry' - 2 records set up.
If we had a flag that we see in admin view to 'hide from main portal' then we could tick that, and if people log in who has access to that it won't show them (doesn't return the record)

**Comment by johndowns** [comment]
Should be possible - I'll take a look.

Would you want the hidden vendors to appear in the admin portal, and/or the CSV export of all vendors?

**Comment by dwdowns** [comment]
Yes and Yes

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
@dwdowns Do you have any rough idea how many businesses might be hidden? Is it likely to be single digits, tens or hundreds?

**Comment by dwdowns** [comment]
Tens, maybe up to a hundred.

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz/>
Check out my TEDx talk<https://www.ted.com/talks/david_downs_don_t_humour_the_tumour_beating_cancer_with_science_and_optimism>.

**Comment by johndowns** [comment]
@JackDownsNZ I've implemented the API side of this (but not fully tested). Are you able to add your front-end code for this onto the same branch please?

**Comment by JackDownsNZ** [comment]
Done - its just front end (only html at this stage) until you let me know what to trigger.

**Comment by johndowns** [comment]
OK cool. You should be able to use a new property called isHidden on the vendor details
