### ISSUE TITLE
Re-order of fields on Vendor list export

### ISSUE THREAD

**Issue by dwdowns** [johndowns/soscafe#71]
If possible, can we reorder the fields in the vendor export to be:

Registered 
Shopify ID 
Business   Name 
Contact   Name 
Email 
Phone   Number 
Bank   Account 
Click   and Collect
Date   Accepted Terms

**Comment by johndowns** [comment]
@dwdowns Where would you like `InternalTag`? After `Date Accepted Terms`?

**Comment by dwdowns** [comment]
Yes thanks

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz/>
Check out my TEDx talk<https://www.ted.com/talks/david_downs_don_t_humour_the_tumour_beating_cancer_with_science_and_optimism>.

**Comment by johndowns** [comment]
Ok, this is done but I'll merge tomorrow alongside the other changes.

**Comment by dwdowns** [comment]
Thank you

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz/>
Check out my TEDx talk<https://www.ted.com/talks/david_downs_don_t_humour_the_tumour_beating_cancer_with_science_and_optimism>.
