### ISSUE TITLE
Add fields for vendor to indicate their open status for each alert level

### ISSUE THREAD

**Issue by joyceqnz** [johndowns/soscafe#73]
This info will be added to their listing so customers can quickly browse and click to their platforms to order C&C/Delivery

**Comment by joyceqnz** [comment]
@johndowns David created this beautiful and succinct graphic of what we need on the vendor portal by tomorrow: https://screenshot.click/20-04-7m9b0-n66o7.png :D Let me know if this is possible

**Comment by JackDownsNZ** [comment]
Frontend Working Branch: `alert-level-status`

**Comment by johndowns** [comment]
@JackDownsNZ I'll start working on this back-end change now. I'll use the same branch as you.

I plan to add the following extra properties to the vendor details API models:

* `level1Closed` (boolean)
* `level1Delivery` (boolean)
* `level1ClickAndCollect` (boolean)
* `level1Open` (boolean)
* `level2Closed` (boolean)
* `level2Delivery` (boolean)
* `level2ClickAndCollect` (boolean)
* `level2Open` (boolean)
* `level3Closed` (boolean)
* `level3Delivery` (boolean)
* `level3ClickAndCollect` (boolean)
* `level3Open` (boolean)
* `clickAndCollectUrl` (string)

As discussed, if it's possible, can you please enforce this business rule on the front end:
* For a given level, if the 'closed' checkbox is selected, none of the other checkboxes can be selected for that level
* For a given level, if the 'closed' checkbox is NOT selected, any combination of the other checkboxes can be selected for that level

**Comment by JackDownsNZ** [comment]
Perfect! I've done the front end side, will need to make a few edits but should work once the backend is going. I'm working in alert-level-status
________________________________

**Comment by johndowns** [comment]
@joyceqnz / @dwdowns  - can you confirm if new vendors should be asked for this information when they sign up, or if it's only able to be edited on existing vendor records?

**Comment by dwdowns** [comment]
Ideally let’s ask them when they register a business too but it’s optional.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johndowns** [comment]
@JackDownsNZ I have opened a PR so that we can test this out. I've got the back-end part done for editing existing vendors. I'll do new vendors shortly. Are you able to do the front-end changes for new vendors too please?

**Comment by johndowns** [comment]
@JackDownsNZ I've implemented the back-end changes to support new vendors having these fields too.

Can I leave this with you to test? I will pick up again later this evening to check out any bugs etc.

**Comment by JackDownsNZ** [comment]
Yep I'll have to take a look later tonight or tomorrow morning though
________________________________

**Comment by dwdowns** [comment]
Thank you fellas

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz/>
Check out my TEDx talk<https://www.ted.com/talks/david_downs_don_t_humour_the_tumour_beating_cancer_with_science_and_optimism>.

**Comment by JackDownsNZ** [comment]
@dwdowns alert level status changes are all live on the test site for vendors (https://soscafevendoruiproxytest.azurewebsites.net/) are you able to go check that it's what you wanted?

Will add to admins also.

**Comment by JackDownsNZ** [comment]
Have added to admin view also - will full edit access.

**Comment by johndowns** [comment]
@joyceqnz Can you please check out the test site (https://soscafevendoruiproxytest.azurewebsites.net/) and see if it looks like what you expect? Currently these fields can only be set for existing vendors, not when new vendors register - but that is coming too.

**Comment by dwdowns** [comment]
Excellent - thank you – these look great!

www.downwithcancer.nz<http://www.downwithcancer.nz/>
Check out my book here: www.mildtouch.nz<http://www.mildtouch.nz>
Check out my TEDx talk<https://tedxauckland.com/talks/reflections-of-a-genetically-modified-optimist/>.

**Comment by johndowns** [comment]
@joyceqnz @dwdowns as per other comment, this is all ready for you to test on the test site (https://soscafevendoruiproxytest.azurewebsites.net/).

Once you are happy we can release this to production.

**Comment by joyceqnz** [comment]
Hey team! Looks great! Just want to confirm these are the specific properties that we can use on Shopify?

**Comment by joyceqnz** [comment]
level1Closed (boolean)
level1Delivery (boolean)
level1ClickAndCollect (boolean)
level1Open (boolean)
level2Closed (boolean)
level2Delivery (boolean)
level2ClickAndCollect (boolean)
level2Open (boolean)
level3Closed (boolean)
level3Delivery (boolean)
level3ClickAndCollect (boolean)
level3Open (boolean)
clickAndCollectUrl (string)

**Comment by johndowns** [comment]
As per earlier discussions this isn’t integrated with Shopify -will be a manual expOrt

**Comment by joyceqnz** [comment]
Hey John, gotcha! Sorry I was thinking about this a different way. No issue with manual export :D Thanks for the beautiful work!!

**Comment by johndowns** [comment]
No worries - I will release this to production later today when I get a few
minutes

**Comment by johndowns** [comment]
This has been released :)

**Comment by joyceqnz** [comment]
Amazing thanks John!
