### ISSUE TITLE
Click and collect checkbox UI bug

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#88]
* Open vendor ID 4350932615224 to see this on production. I haven't replicated on a test vendor but I expect you can do it by adding a click & collect URL to the vendor then reopening the edit vendor UI.
* Uncheck 'I already have click & collect set up'
* Notice that the 'I am interested in setting up click & collect' reappears, but is pre-checked. If you uncheck it, it doesn't actually uncheck and the URL box reappears.

@JackDownsNZ Could you take a look please?

**Comment by JackDownsNZ** [comment]
Looking into now.

**Comment by JackDownsNZ** [comment]
Logic was too complicated for such a simple user choice. Have removed and changed to basic UI.

**Comment by JackDownsNZ** [comment]
Working Branch: `bug-fixes`

Will PR once I have also fixed #92
