### ISSUE TITLE
Weirdness in display of refunded vouchers

### ISSUE THREAD

**Issue by dwdowns** [johndowns/soscafe#92]
Here is another wee conundrum though – check out vendor
4350043095096
 
Row key
4337079418936
 
In Azure it has (correctly) this for the voucher ID
** REFUNDED AE00-E529-79C2-E368-4763
 
But in the portal it is displaying it like
REFUNDED AE00-E529-79C2-E368-4763 **
 
And weirdly if you copy it from the portal and paste it somewhere it displays as
** REFUNDED AE00-E529-79C2-E368-4763

**Comment by johndowns** [comment]
@JackDownsNZ could you please take a look - I think this is due to the way the right alignment and truncation of that column works

**Comment by JackDownsNZ** [comment]
Woah weird indeed! Will look into it.
