### ISSUE TITLE
Look at sort order of voucher IDs

### ISSUE THREAD

**Issue by johndowns** [johndowns/soscafe#93]
The client-side sorting of vouchers seems to have an oddity when handling the voucher ID column. For example, see the business 'Crave' (ID 4349746282552).

Nik advised that the sort order only works well for strings, so potentially this requires replacing the Angular Material sorting component?

**Comment by blckqdrnt** [comment]
Hi @johndowns could you please identify the oddity?

Ascending should be: Special Characters > [0-9] > [A-Z]
![image](https://user-images.githubusercontent.com/64027058/80379707-8c910980-88f2-11ea-8219-16ecafda4675.png)

Descending should be: [Z-A] > [9-0] > Special Characters
![image](https://user-images.githubusercontent.com/64027058/80379752-a16d9d00-88f2-11ea-9d12-863b63f743f2.png)

Seems to be working fine for me, am I missing something?

**Comment by blckqdrnt** [comment]
Hi @johndowns I've figured out what the oddity is.

![image](https://user-images.githubusercontent.com/64027058/80385711-8737bd00-88fa-11ea-8fc9-45de3f1ce8bc.png)

There are some voucher IDs which are all numbers. These are the ids which are displaying the oddity of not being sorted. If I suffix a string (in the above picture, I have suffixed "-"), these ids are sortable again. 

My recommendation is, do not replace the paginator (it would take too much effort for too little value addition). Instead, force voucher ids, or any ids to have atleast one alphabetic character. I've pushed a branch "sortable-oddity" which shows the logic in vendor-vouchers.components.ts:56

**Comment by blckqdrnt** [comment]
@johndowns what do you think about this?

**Comment by johndowns** [comment]
@blckqdrnt sorry for the delay! As it happens we have revised the way vouchers are imported, and in the process I have made a change to ensure that we always use alphanumeric voucher IDs. So I think this should take care of the issue based on your investigation. I will leave the issue open until I confirm once we deploy the change though.

**Comment by blckqdrnt** [comment]
Cool. Let me know if there's anything else I can help with
